package unittest

import (
	"os"
	"path/filepath"
	"sekawan-backend/app/main/enum"
	"sekawan-backend/app/main/handlerAuth"
	"sekawan-backend/app/main/util"
	"strconv"
	"testing"
	"time"

	"github.com/goccy/go-json"
	"github.com/google/uuid"
	"github.com/joho/godotenv"
)

type OS interface {
	Getenv(string) string
}

type defaultOS struct{}

func (defaultOS) Getenv(key string) string {
	return os.Getenv(key)
}

const (
	clientId  = "ari_aprasetiyo_client_id_1234"
	clientKey = "Hfxp$kK1o4z=$W+U_Se0rEasGk2E_Rt6sH7xCR7rf4-E7Ilm6nizei+OtEOsKyPbZk4kn+r4NagzeI3kOKWhMximK!KUVb6Pdun8"
)

/*
client requirements
1. phoneNo = generated by request
2. password = generated by request
3. clientId = generated by system
4. clientKey = generated by system
5. clientKeyPattern = static
*/
func TestCurlRequestGenerateToken(t *testing.T) {
	godotenv.Load()
	err := godotenv.Load(filepath.Join("../../", ".env.example"))
	util.IsErrorDoPrint(err)
	clientKeyPattern := os.Getenv(util.CONFIG_APP_API_CLIENT_KEY_PATTERN)

	secretKeySHA256 := clientId + clientKeyPattern + clientKey
	encryptionKey := os.Getenv(util.CONFIG_APP_ENCRIPTION_KEY)

	phoneNo := "+6285600070411"
	password := "cobacoba1-="
	authCredRequest := handlerAuth.AuthCredRequest{PhoneNo: phoneNo, Password: password}
	authCredRequestInJson, err := json.Marshal(authCredRequest)
	util.IsErrorDoPrint(err)
	encryptionCredential := util.EncryptAES256(encryptionKey, string(authCredRequestInJson))
	requestId := uuid.New().String()
	requestTime := time.Now().UnixMilli()

	var bodyRequest = "{\"requestId\":\"" + requestId + "\",\"type\":\"" + enum.TYPE_GENERATE_TOKEN.String() + "\",\"requestTime\":" + strconv.FormatInt(requestTime, 10) + ",\"body\":{\"cred\":\"" + encryptionCredential + "\"}}"
	signature := util.HmacSha256(secretKeySHA256, bodyRequest)
	curl := "curl -X POST localhost:8083/public/token -H 'Msg-Id: " + requestId + "' -H 'Client-Id: " + clientId + "' -H 'Signature: " + signature + "' -d '" + bodyRequest + "'"
	println(curl)
}

/*
client requirements
1. jwtToken = generated by request
3. clientId = generated by system
4. clientKey = generated by system
5. clientKeyPattern = static
*/
func TestCurlRequestGenerateHTTPGet(t *testing.T) {
	godotenv.Load()
	err := godotenv.Load(filepath.Join("../../", ".env.example"))
	util.IsErrorDoPrint(err)
	clientKeyPattern := os.Getenv(util.CONFIG_APP_API_CLIENT_KEY_PATTERN)

	requestId := uuid.New().String()
	url := "/api/v1/test/get?name=test&type=" + enum.TYPE_REQUEST_HTTP_GET_TEST.String()
	jwtToken := "eyJib2R5Ijp7InVzZXJJZCI6IjhBUlNnWXIxb2ZGUkdKcnhvQWdhIiwiZXhwaXJlZFRzIjoxNjk3Mzg0NTU0OTE4LCJhY2wiOjB9LCJzaWduYXR1cmUiOiIwM2RmZjZjNDNjZGQxMDExZWYwZjkzN2FjNGU1ODdkY2MwMmNjM2EzZDZjZjQ5YTkyMmJhYjNiYWI5NDY4OGIwIn0="

	clientIdServerSide := clientId
	secretKeySHA256 := clientIdServerSide + clientKeyPattern + jwtToken

	signature := util.HmacSha256(secretKeySHA256, url)
	curl := "curl -X GET 'localhost:8083" + url + "' -H 'Msg-Id: " + requestId + "' -H 'Client-Id: " + clientIdServerSide + "' -H 'Signature: " + signature + "' -H 'Authorization: " + jwtToken + "'"
	println(curl)
}

/*
client requirements
1. jwtToken = generated by request
3. clientId = generated by system
4. clientKey = generated by system
5. clientKeyPattern = static
*/
func TestCurlRequestGenerateHTTPPost(t *testing.T) {
	godotenv.Load()
	err := godotenv.Load(filepath.Join("../../", ".env.example"))
	util.IsErrorDoPrint(err)
	clientKeyPattern := os.Getenv(util.CONFIG_APP_API_CLIENT_KEY_PATTERN)

	requestId := uuid.New().String()
	requestTime := time.Now().UnixMilli()
	name := "ari prasetiyo"
	url := "/api/v1/test/post"
	var bodyRequest = "{\"requestId\":\"" + requestId + "\",\"type\":\"" + enum.TYPE_REQUEST_HTTP_POST_TEST.String() + "\",\"requestTime\":" + strconv.FormatInt(requestTime, 10) + ",\"body\":{\"name\":\"" + name + "\"}}"
	jwtToken := "eyJib2R5Ijp7InVzZXJJZCI6IjhBUlNnWXIxb2ZGUkdKcnhvQWdhIiwiZXhwaXJlZFRzIjoxNjk1OTEzMzk0NDA0LCJhY2wiOjB9LCJzaWduYXR1cmUiOiIzMTIyNjM5MDdmZWY2YmJmNWU3M2UyMTE4Y2M0NTQ2ZmFkZDZkZGVlMjJiMGE1YmRkZGYyNTg0ZWFkM2JlZDQxIn0="

	clientIdServerSide := clientId
	secretKeySHA256 := clientIdServerSide + clientKeyPattern + jwtToken

	signature := util.HmacSha256(secretKeySHA256, bodyRequest)
	curl := "curl -X POST 'localhost:8083" + url + "' -H 'Content-Type: application/json' -H 'Msg-Id: " + requestId + "' -H 'Client-Id: " + clientIdServerSide + "' -H 'Signature: " + signature + "' -H 'Authorization: " + jwtToken + "' -d '" + bodyRequest + "' "
	println(curl)
}
